FROM node:latest as build
COPY package.json package-lock.json ./
RUN npm install && mkdir /build && mv ./node_modules ./build
WORKDIR /build
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /build/dist/* /usr/share/nginx/html
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginx.dev.conf /etc/nginx/conf.d
EXPOSE 80 443
ENTRYPOINT ["nginx", "-g", "daemon off;"]
